### ISSUE TITLE
Animal and Press Release help drop-down do not appear on the main back-end post-type display page

### ISSUE THREAD

**Issue by thisisjoewells** [TheDetroitZoo/help#5]
Hi.
I'm learning about GitHub here.  I figure tweaking stuff on the Help plugin is the place to start.
Leave this one to me (Joe).

On the back-end - I'd like the help drop-downs to be visible on both the post-type listing page and of course the actual edit/add-new post pages.  Right now the Animal and Press Release help pages only show up on the edit/add-new post pages.

Not on listing page:
![help-animal-issue1](https://cloud.githubusercontent.com/assets/9747248/12796753/692653e6-ca8e-11e5-9eb1-d83ca0498550.jpg)

Just on edit/add-new post:
![help-animal-issue2](https://cloud.githubusercontent.com/assets/9747248/12796773/84c80fd6-ca8e-11e5-8573-fca3c4df0db4.jpg)

I'll see if I can do this, and we can all watch my commits in good ol' GitHub.

**Comment by joelworsham** [comment]
I'm certain it's possible, probably via a different file naming scheme. I will look into this

**Comment by joelworsham** [comment]
Alrighty, here's what to do. If you ever want to add a help tab to a screen, go to that screen and then hover over the Query Monitor toolbar node (in the top screenshot it says "2.55s 43.47mb 0.1070s 237Q". Then click on "Admin Screen". You should see a box on the right that has the heading "Admin Screen", and under that on the left it says get_current_screen(), then on the right there's a bunch of rows. The row that is labeled "id" is what you're interested in. Take that "id" text and make it your file name. So, for instance, on the dashboard that "id" says "dashboard". So to make a help tab for the dashboard, name your file "dashboard.html".

So, in this instance, copy your file "animal.html" to a new file called "edit-animal.html" and make adjustments to the contents as necessary.
