### ISSUE TITLE
The folder for this plugin is 'help-master' instead of 'help'

### ISSUE THREAD

**Issue by thisisjoewells** [TheDetroitZoo/help#6]
Please instruct me how to fix this.  Remember 'Help' is my new GitHub learning ground.

This may be as simple as renaming the folder on the server/s and nothing else?

**Comment by joelworsham** [comment]
Yessir, go ahead and rename the folder and then re-activate the plugin after doing so

**Comment by thisisjoewells** [comment]
Done on staging, tested, good.  Done on live.

**Comment by joelworsham** [comment]
:+1:
