### ISSUE TITLE
This is a Sample Issue

### ISSUE THREAD

**Issue by thisisjoewells** [TheDetroitZoo/help#7]
I have found an error on the website.  The Today At the Zoo dropdown needs to be able to do XYZ.

Can we fix this?

**Comment by brashrebel** [comment]
Experimenting or something?

**Comment by brashrebel** [comment]
Absolutely @thisisjoewells! We'll take care of this right away.

**Comment by brashrebel** [comment]
Thanks for pointing out this issue @thisisjoewells. We've patched the bug and pushed the changes to the staging site. Can you test and let us know if we can deploy to production please?

**Comment by joelworsham** [comment]
I am thoroughly confused, but I like it.

**Comment by thisisjoewells** [comment]
Thanks @brashrebel.  I've tested it on staging.  The fix is great.  Good work.

You can push to live today when you do your next push.
